apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-api-config
data:
  RabbitMq__Host: rabbitmq
  RabbitMq__Username: guest
  RabbitMq__OrderPlacedQueue: payments-order-placed
  Payments__ForceRejected: "false"
